# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  deploy: dosomething/deploy@0.0.3

jobs:
  # Install dependencies, run tests, and compile for Lambda.
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: npm run compile
      # When we're on npm 5.7+, add this back in. <https://git.io/fhMbF>
      # - run: npm prune --production
      - deploy/store-lambda

# Configure workflows & scheduled jobs:
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - deploy-dev
            - deploy-qa
          filters:
            branches:
              only: circleci-workflow
      - deploy/deploy-lambda:
          name: deploy-dev
          app: dosomething-graphql-dev
          working_directory: ~/app
          requires:
            - build
          filters:
            branches:
              only: circleci-workflow
      - deploy/deploy-lambda:
          name: deploy-qa
          app: dosomething-graphql-qa
          working_directory: ~/app
          requires:
            - build
          filters:
            branches:
              only: circleci-workflow
      - deploy/deploy-lambda:
          name: deploy-production
          app: dosomething-graphql
          working_directory: ~/app
          requires:
            - hold
          filters:
            branches:
              only: circleci-workflow
