# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  lambda: dosomething/lambda@0.0.3

jobs:
  # Install dependencies, run tests, and compile for Lambda.
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: npm run compile
      # When we're on npm 5.7+, add this back in. <https://git.io/fhMbF>
      # - run: npm prune --production
      - lambda/store
  publish:
    parameters:
      endpoint:
        type: string
      key:
        type: env_var_name
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: npm install
      - run:
          name: publish schema to apollo engine
          command: npm run service:push --  --endpoint=<<parameters.endpoint>> --key=${<<parameters.key>>}

# Configure workflows & scheduled jobs:
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - deploy-app-dev
            - deploy-webhook-dev
            - deploy-app-qa
            - deploy-webhook-qa
          filters:
            branches:
              only: master
      - lambda/deploy:
          name: deploy-app-dev
          app: dosomething-graphql-dev
          requires:
            - build
          filters:
            branches:
              only: master
      - lambda/deploy:
          name: deploy-webhook-dev
          app: dosomething-graphql-dev-webhook
          requires:
            - build
          filters:
            branches:
              only: master
      - lambda/deploy:
          name: deploy-app-qa
          app: dosomething-graphql-qa
          requires:
            - build
          filters:
            branches:
              only: master
      - lambda/deploy:
          name: deploy-webhook-qa
          app: dosomething-graphql-qa-webhook
          requires:
            - build
          filters:
            branches:
              only: master
      - lambda/deploy:
          name: deploy-app-production
          app: dosomething-graphql
          requires:
            - hold
          filters:
            branches:
              only: master
      - lambda/deploy:
          name: deploy-webhook-production
          app: dosomething-graphql-webhook
          requires:
            - hold
          filters:
            branches:
              only: master
      - publish:
          name: publish-app-dev
          endpoint: https://graphql-dev.dosomething.org/graphql
          key: ENGINE_KEY_DEVELOPMENT
          requires:
            - deploy-app-dev
      - publish:
          name: publish-app-qa
          endpoint: https://graphql-qa.dosomething.org/graphql
          key: ENGINE_KEY_QA
          requires:
            - deploy-app-qa
      - publish:
          name: publish-app-production
          endpoint: https://graphql.dosomething.org/graphql
          key: ENGINE_KEY_PRODUCTION
          requires:
            - deploy-app-production
