# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  - deploy: dosomething/deploy@dev:master

jobs:
  # Install dependencies, run tests, and compile for Lambda.
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
      - run: npm run compile
      # When we're on npm 5.7+, add this back in. <https://git.io/fhMbF>
      # - run: npm prune --production
      - run:
          name: Compress source
          command: cd ~/app && zip -r release.zip .
      - persist_to_workspace:
          root: .
          paths:
            - release.zip


  # Base job to deploy to a Lambda function. <https://goo.gl/iDdcpb>
  # We use a '&deploy' reference to clone this for each environment.
  deploy: &deploy
    docker:
      - image: circleci/python:3.6
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: ~/app
      - deploy/lambda

  # Configure environment-specific deploy jobs with reference.
  deploy-dev:
    <<: *deploy
    environment:
      APP_NAME: dosomething-graphql-dev
  deploy-qa:
    <<: *deploy
    environment:
      APP_NAME: dosomething-graphql-qa
  deploy-production:
    <<: *deploy
    environment:
      APP_NAME: dosomething-graphql


# Configure workflows & scheduled jobs:
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - deploy-dev
            - deploy-qa
          filters:
            branches:
              only: circleci-workflow
      - deploy-dev:
          requires:
            - build
          filters:
            branches:
              only: circleci-workflow
      - deploy-qa:
          requires:
            - build
          filters:
            branches:
              only: circleci-workflow
      - deploy-production:
          requires:
            - hold
          filters:
            branches:
              only: circleci-workflow
